#defaults: &defaults
#  allow_dynamic_fields: true
#  parameterize_keys: true
#  persist_in_safe_mode: true
#  raise_not_found_error: true
#  reconnect_time: 3
#  use_object_ids: false
#
development:
  identity_map_enabled: true
  host: localhost
  database: bemscape_test

test:
  host: localhost
  database: bemscape_test

# set these environment variables on your prod server
#E-WATTS
production:
  host: <%= ENV['MONGO_HOST'] %>
  port: <%= ENV['MONGO_PORT'] %>
  username: <%= ENV['MONGO_BEMSCAPE_USERNAME'] %>
  password: <%= ENV['MONGO_BEMSCAPE_PASSWORD'] %>
  database: bemscape_test
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
