#defaults: &defaults
#  allow_dynamic_fields: true
#  parameterize_keys: true
#  persist_in_safe_mode: true
#  raise_not_found_error: true
#  reconnect_time: 3
#  use_object_ids: false
#
development:
  identity_map_enabled: true
  database: bemscape_test
  host: zerodev-128488.nrel.gov
  port: 27018
  #replica_set:
  #  host: zerodev-128488.nrel.gov:27019
  #  host: zerodev-128488.nrel.gov:27020
  ##  - - zerodev-128488.nrel.gov
  ##    - 27020
  #read_secondary: true
  #
test:
  host: localhost
  database: bemscape_test

# set these environment variables on your prod server
# e-watts (on e-demeter) and rordev (on devmongo1-1.development.nrel.gov)
production:
  host: <%= ENV['MONGO_HOST'] %>
  port: <%= ENV['MONGO_PORT'] %>
#  username: <%= ENV['MONGO_BEMSCAPE_USERNAME'] %>
#  password: <%= ENV['MONGO_BEMSCAPE_PASSWORD'] %>
  database: bemscape_test
  #hosts:
  #  - - devmongo1-2.development.nrel.gov
  #    - 27017
  #  - - devmongo1-3.development.nrel.gov
  #    - 27017
  #read_secondary: true